// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TristanRosel.EntityFramework;

#nullable disable

namespace TristanRosel.EntityFramework.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20241030022843_Innit")]
    partial class Innit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TristanRosel.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .HasColumnType("longtext");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("BookId");

                    b.HasIndex("LibraryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("d9d9cc58-1541-4a41-9998-bea0cb269875"),
                            Author = "John Doe",
                            ISBN = "123-4567890123",
                            LibraryId = new Guid("5f01c9e9-c1f8-42f7-8475-4e8ddc284e09"),
                            Title = "C# Programming"
                        },
                        new
                        {
                            BookId = new Guid("cae432ce-f873-4a19-987f-2adf1eadd387"),
                            Author = "Thomas H. Cormen",
                            ISBN = "456-7890123456",
                            LibraryId = new Guid("7e90bb85-f4b4-4c50-ae3f-ab02d676e528"),
                            Title = "Introduction to Algorithms"
                        });
                });

            modelBuilder.Entity("TristanRosel.Models.Library", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("LibraryId");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            LibraryId = new Guid("5f01c9e9-c1f8-42f7-8475-4e8ddc284e09"),
                            EstablishedYear = 1950,
                            Location = "Downtown",
                            Name = "Central Library"
                        },
                        new
                        {
                            LibraryId = new Guid("7e90bb85-f4b4-4c50-ae3f-ab02d676e528"),
                            EstablishedYear = 1980,
                            Location = "Suburbs",
                            Name = "Community Library"
                        });
                });

            modelBuilder.Entity("TristanRosel.Models.Book", b =>
                {
                    b.HasOne("TristanRosel.Models.Library", "Library")
                        .WithMany("Books")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("TristanRosel.Models.Library", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
